import type { Metadata } from "next";
import { Montserrat, Passion_One } from "next/font/google";

import "./globals.css";

const montserratSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const passion_oneSans = Passion_One({
  subsets: ["latin"],
  variable: "--font-passion-one",
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable} ${passion_oneSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
